export const GIFT_LIST_REQUEST = "GIFT_LIST_REQUEST";
export const GIFT_LIST_SUCCESS = "GIFT_LIST_SUCCESS";
export const GIFT_LIST_FAIL = "GIFT_LIST_FAIL";

export const GIFT_DETAILS_REQUEST = "GIFT_DETAILS_REQUEST";
export const GIFT_DETAILS_SUCCESS = "GIFT_DETAILS_SUCCESS";
export const GIFT_DETAILS_FAIL = "GIFT_DETAILS_FAIL";

export const GIFT_CREATE_REVIEW_REQUEST = "GIFT_CREATE_REVIEW_REQUEST";
export const GIFT_CREATE_REVIEW_SUCCESS = "GIFT_CREATE_REVIEW_SUCCESS";
export const GIFT_CREATE_REVIEW_FAIL = "GIFT_CREATE_REVIEW_FAIL";
export const GIFT_CREATE_REVIEW_RESET = "GIFT_CREATE_REVIEW_RESET";
