export const INVITATION_LIST_REQUEST = "INVITATION_LIST_REQUEST";
export const INVITATION_LIST_SUCCESS = "INVITATION_LIST_SUCCESS";
export const INVITATION_LIST_FAIL = "INVITATION_LIST_FAIL";

export const INVITATION_DETAILS_REQUEST = "INVITATION_DETAILS_REQUEST";
export const INVITATION_DETAILS_SUCCESS = "INVITATION_DETAILS_SUCCESS";
export const INVITATION_DETAILS_FAIL = "INVITATION_DETAILS_FAIL";

export const INVITATION_CREATE_REVIEW_REQUEST = "INVITATION_CREATE_REVIEW_REQUEST";
export const INVITATION_CREATE_REVIEW_SUCCESS = "INVITATION_CREATE_REVIEW_SUCCESS";
export const INVITATION_CREATE_REVIEW_FAIL = "INVITATION_CREATE_REVIEW_FAIL";
export const INVITATION_CREATE_REVIEW_RESET = "INVITATION_CREATE_REVIEW_RESET";
