export const INVITATION_LIST_REQUEST = "INVITATION_LIST_REQUEST";
export const INVITATION_LIST_SUCCESS = "INVITATION_LIST_SUCCESS";
export const INVITATION_LIST_FAIL = "INVITATION_LIST_FAIL";

export const INVITATION_EDIT_REQUEST = "INVITATION_EDIT_REQUEST";
export const INVITATION_EDIT_SUCCESS = "INVITATION_EDIT_SUCCESS";
export const INVITATION_EDIT_FAIL = "INVITATION_EDIT_FAIL";

export const INVITATION_DELETE_REQUEST = "INVITATION_DELETE_REQUEST";
export const INVITATION_DELETE_SUCCESS = "INVITATION_DELETE_SUCCESS";
export const INVITATION_DELETE_FAIL = "INVITATION_DELETE_FAIL";

export const INVITATION_CREATE_REQUEST = "INVITATION_CREATE_REQUEST";
export const INVITATION_CREATE_SUCCESS = "INVITATION_CREATE_SUCCESS";
export const INVITATION_CREATE_FAIL = "INVITATION_CREATE_FAIL";
export const INVITATION_CREATE_RESET = "INVITATION_CREATE_RESET";

export const INVITATION_UPDATE_REQUEST = "INVITATION_UPDATE_REQUEST";
export const INVITATION_UPDATE_SUCCESS = "INVITATION_UPDATE_SUCCESS";
export const INVITATION_UPDATE_FAIL = "INVITATION_UPDATE_FAIL";
export const INVITATION_UPDATE_RESET = "INVITATION_UPDATE_RESET";
